//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointHistory
    {
        public int PointHistoryID { get; set; }
        public int CustomerID { get; set; }
        public int Points { get; set; }
        public string TransactionType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RelatedAmount { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
