//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatTemplate()
        {
            this.CinemaRooms = new HashSet<CinemaRoom>();
            this.Seats = new HashSet<Seat>();
        }
    
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> ColumnCount { get; set; }
        public Nullable<int> NormalRows { get; set; }
        public Nullable<int> VipRows { get; set; }
        public Nullable<int> CoupleRows { get; set; }
        public Nullable<int> Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinemaRoom> CinemaRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
