//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int SeatID { get; set; }
        public int TemplateID { get; set; }
        public string SeatCode { get; set; }
        public int RowNumber { get; set; }
        public int ColumnNumber { get; set; }
        public byte SeatType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SeatTemplate SeatTemplate { get; set; }
    }
}
