//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFood
    {
        public int TicketFoodID { get; set; }
        public int TicketID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Food Food { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
